"""
ZeroGraph AI — Citation & Evidence Validation Service
Validates every [msg_xxxxxx] citation generated by local LLM against real database records.
Rejects hallucinated citations and calculates Evidence Coverage & Citation Precision scores.
Developer: kzsamir
"""

import logging
import re
from database.connection import get_connection

logger = logging.getLogger(__name__)


class CitationValidator:
    """Strict validator for LLM evidence citations and factual coverage."""

    def __init__(self, workspace_id: str = "ws_default"):
        self.workspace_id = workspace_id

    def validate_brief(self, brief_data: dict, retrieved_evidence_ids: list):
        """
        Validate full Evidence-to-Action brief JSON.
        Returns:
            {
                "valid": bool,
                "evidence_coverage_percent": float,
                "citation_precision_percent": float,
                "total_claims": int,
                "supported_claims": int,
                "unsupported_claims": int,
                "all_cited_ids": list,
                "invalid_cited_ids": list,
                "unsupported_warnings": list
            }
        """
        conn = get_connection()

        # Fetch set of valid message IDs in database
        db_rows = conn.execute("SELECT id FROM messages WHERE workspace_id = ?", (self.workspace_id,)).fetchall()
        valid_db_ids = {r["id"] for r in db_rows}
        retrieved_set = set(retrieved_evidence_ids)

        all_cited_ids = set()
        findings = brief_data.get("findings", [])
        actions = brief_data.get("actions", [])

        # Collect citations from findings
        for f in findings:
            ev_ids = f.get("evidence_ids", [])
            for eid in ev_ids:
                all_cited_ids.add(eid)

        # Collect citations from actions
        for a in actions:
            ev_ids = a.get("evidence_ids", [])
            for eid in ev_ids:
                all_cited_ids.add(eid)

        # Also regex extract any [msg_xxxxxx] from summary text
        summary_text = brief_data.get("executive_summary_bn", "")
        extracted_from_summary = re.findall(r'msg_\d+', summary_text)
        all_cited_ids.update(extracted_from_summary)

        # Check citation validity
        invalid_cited_ids = []
        out_of_retrieval_ids = []

        for cid in all_cited_ids:
            if cid not in valid_db_ids:
                invalid_cited_ids.append(cid)
            elif cid not in retrieved_set:
                out_of_retrieval_ids.append(cid)

        # Score calculation
        total_claims = len(findings) + (1 if brief_data.get("executive_summary_bn") else 0)
        unsupported_count = len(invalid_cited_ids)
        supported_count = max(0, total_claims - unsupported_count)

        coverage_percent = round((supported_count / max(1, total_claims)) * 100, 1)
        precision_percent = round(((len(all_cited_ids) - len(invalid_cited_ids)) / max(1, len(all_cited_ids))) * 100, 1)

        warnings = []
        if invalid_cited_ids:
            warnings.append(f"অস্তিত্বহীন মেসেজ আইডি পাওয়া গেছে: {', '.join(invalid_cited_ids)}")
        if out_of_retrieval_ids:
            warnings.append(f"আহৃত তালিকার বাইরের আইডি সাইট করা হয়েছে: {', '.join(out_of_retrieval_ids)}")
        if brief_data.get("requires_human_review"):
            warnings.append("উচ্চ-ঝুঁকি বা ইনফারেন্স উপাদানের কারণে মানব পর্যালোচনা বাধ্যতামূলক।")

        is_valid = len(invalid_cited_ids) == 0

        return {
            "valid": is_valid,
            "evidence_coverage_percent": coverage_percent,
            "citation_precision_percent": precision_percent,
            "total_claims": total_claims,
            "supported_claims": supported_count,
            "unsupported_claims": unsupported_count,
            "all_cited_ids": sorted(list(all_cited_ids)),
            "invalid_cited_ids": invalid_cited_ids,
            "out_of_retrieval_ids": out_of_retrieval_ids,
            "warnings_bn": warnings
        }
